# Generated by Django 5.1.2 on 2024-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(blank=True, max_length=50, null=True)),
                ('BImage', models.ImageField(blank=True, null=True, upload_to='blog_img')),
            ],
        ),
    ]
